org: wildflowerschools
app: wf-google-workspace-api
service: aws-python-flask-api-project

frameworkVersion: '3'

useDotenv: true

custom:
  wsgi:
    app: app.app
    pythonBin: python

provider:
  name: aws
  runtime: python3.9
  environment:
    GOOGLE_WORKSPACE_SERVICE_ACCOUNT_CREDENTIALS: ${env:GOOGLE_WORKSPACE_SERVICE_ACCOUNT_CREDENTIALS}
    GOOGLE_WORKSPACE_SERVICE_ACCOUNT_DELEGATED_USER: ${env:GOOGLE_WORKSPACE_SERVICE_ACCOUNT_DELEGATED_USER}
    GOOGLE_WORKSPACE_CUSTOMER_ID: ${env:GOOGLE_WORKSPACE_CUSTOMER_ID}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
