import os

GOOGLE_WORKSPACE_SERVICE_ACCOUNT_CREDENTIALS = os.getenv(
    "GOOGLE_WORKSPACE_SERVICE_ACCOUNT_CREDENTIALS", None)

GOOGLE_WORKSPACE_SERVICE_ACCOUNT_DELEGATED_USER = os.getenv(
    "GOOGLE_WORKSPACE_SERVICE_ACCOUNT_DELEGATED_USER", None)

GOOGLE_WORKSPACE_CUSTOMER_ID = os.getenv(
    "GOOGLE_WORKSPACE_CUSTOMER_ID", None
)

AUTH0_AUDIENCE = os.getenv(
    "AUTH0_AUDIENCE", None)

AUTH0_DOMAIN = os.getenv(
    "AUTH0_DOMAIN", None)

STAGE = os.getenv(
    "STAGE", 'dev')
